# Generated by Django 4.0 on 2022-04-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_name',
            field=models.CharField(db_index=True, max_length=25, null=True, unique=True),
        ),
    ]
