# Generated by Django 4.0 on 2022-04-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contest_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('contest_duration', models.IntegerField(blank=True, default=120)),
                ('name', models.CharField(default='Codeforces Round #0', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('contest_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('rating_delta', models.IntegerField()),
                ('virtually', models.BooleanField(default=False)),
            ],
        ),
    ]
