# Generated by Django 4.0 on 2022-04-07 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
