# Generated by Django 4.0 on 2022-04-05 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('contest_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('rating_delta', models.IntegerField()),
                ('virtually', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
