# Generated by Django 4.0 on 2022-01-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='tag', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField(default=0)),
                ('index', models.CharField(default=0, max_length=10)),
                ('name', models.CharField(default='Mike', max_length=100)),
                ('rating', models.IntegerField(default=1400)),
                ('solve_count', models.PositiveIntegerField(default=0)),
                ('tags', models.ManyToManyField(to='problem.Tag')),
            ],
        ),
    ]
