# Generated by Django 4.0 on 2022-04-10 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_team', to='team.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_team', to='team.team'),
        ),
    ]
